# directory containing the data for each task
bench_data_root: '/home/than/.cache/huggingface/hub/datasets--MahmoodLab--hest-bench/snapshots/d04c8a09d5e3991cc1105e7c1b925bbc7025ae7c'

# directory where benchmark results will be dumped
results_dir: 'ST_pred_results'

# directory where the vision embeddings will be dumped
embed_dataroot: 'ST_data_emb'

# directory to the model weights root
weights_root: '/home/than/.cache/huggingface/hub/datasets--MahmoodLab--hest-bench/snapshots/d04c8a09d5e3991cc1105e7c1b925bbc7025ae7c/fm_v1/'

# inference parameters
batch_size: 128
num_workers: 1

# encoders to benchmark
encoders: [
  #"plip",
  #"uni_v1", # uncomment after requesting the weights
  #"resnet50",
  "ctranspath",
  #"phikon",
  #"remedis", # uncomment after requesting the weights
  #"conch_v1", # uncomment after requesting the weights
  #"gigapath", # uncomment after requesting the weights
  #"virchow", # uncomment after requesting the weights
  #"virchow2", # uncomment after requesting the weights
  #"hoptimus0",
]

# datasets contained in `bench_data_root` to benchmark
datasets: [
  "IDC",
  # "PRAD",
  # "PAAD",
  # "SKCM",
  # "COAD",
  # "READ",
  # "CCRCC",
  # "HCC",
  # "LUNG",
  # "LYMPH_IDC",
]

#dimreduce: "PCA" 
save_assets: True 
gene_padding: True